language: php

php:
  - 5.4
  - 5.5

before_script:
  - pyrus set auto_discover 1
  - pyrus install --force phpunit/DbUnit
  - phpenv rehash

script: phpunit --configuration phpunit.xml --coverage-text
