language: php

php:
  - 5.3
  - 5.4

before_script:
  - pyrus config-set auto_discover 1
  - pyrus install phpunit/DbUnit
  - phpenv rehash

script: phpunit --configuration phpunit.xml --coverage-text
